runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /assets
  static_dir: assets

- url: .*
  script: main.application

- url: /css
  static_dir: css

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
